databases:
  - name: techstore-db
    plan: free
    databaseName: techstore
    user: techstore_user

services:
  - type: web
    name: techstore-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: APP_NAME
        value: TechStore
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: techstore-api
          property: host
          prefix: https://
      - key: FRONTEND_URL
        fromService:
          type: web
          name: techstore-frontend
          property: host
          prefix: https://
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: techstore-db
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: techstore-db
          property: connectionString
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: SANCTUM_STATEFUL_DOMAINS
        value: ""
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false

  - type: web
    name: techstore-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: techstore-api
          property: host
          prefix: https://
          suffix: /api
      - key: VITE_STRIPE_KEY
        sync: false
